config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'sakes/index'
  end
  root to: 'public/homes#top'
  get "about" => "public/homes#about"
  get "admin" => "admin/homes#top"

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン機能
  devise_scope :customer do
    post 'public/guest_login', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only:[:index,:create,:edit,:update,:destroy]
    resources :sakes, only:[:show,:index,:destroy] do
      resources :sake_comments, only:[:destroy]
    end
    resources :customers, only:[:index,:show,:edit,:update]
    get "homes/about" => "homes#about"
    post "homes/about" => "homes#create"
    resources :homes, only:[:create,:edit,:update,:destroy]
  end

  scope module: :public do
    resources :genres, only:[:index]
    get 'search' => 'searches#search'
    get 'genre_search' => 'sakes#genre_search'
    resources :sakes, only:[:index,:show,:destroy,:edit,:update,:create,:new] do
      resources :sake_comments, only:[:edit,:update,:destroy,:create]
      resource :favorites, only:[:create,:destroy]
      resource :bookmarks, only:[:create,:destroy]
      get 'search' => "genres#search"
    end
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/delete_status' => 'customers#is_deleted'
    resources :customers, only:[:index,:show,:destroy,:edit,:update,:create] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      resource :relationships, only:[:destroy,:create]
    end
    resources :chats, only:[:show, :create]
    resources :tags, only:[:create,:destroy]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sakes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :sake_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :dm_rooms
  has_many :chats
  has_many :room, through: :dm_rooms

  validates :name, presence:true, length: { minimum: 1, maximum: 20 }
  validates :email, presence:true

  has_one_attached :profile_image

  # 画像ファイルについて
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # ゲストログイン機能
  def self.guest
    find_or_create_by!(name: 'guest' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guest"
    end
  end

  # フォローフォロワー機能
  def follow(customer)
    relationships.create(followed_id: customer.id)
  end

  def unfollow(customer)
    relationships.find_by(followed_id: customer.id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end

  #退会機能
  # is_deletedがfalseならtrueを返すようにしている
  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約を設ける
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("name LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報の更新に成功しました。"
      redirect_to admin_customers_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name,:introduction,:email,:profile_image,:is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="row mx-5 mt-4 mx-auto justify-content-center">
  <div class="col-md-6 text-left">
    <h4><strong>会員情報の変更</strong></h4>
  </div>
</div>

<div class="row mb-5 mx-auto justify-content-center">
  <div class="col-md-10 mt-3" >
    <%= render 'layouts/errors', obj: @customer %>
  </div>
</div>

<%= form_with model: [:admin, @customer], local: true do |f| %>
  <div class="row mx-5 mt-4 mx-auto justify-content-center">
    <div class="col-md-2">
      <%= f.label :プロフィール画像 %>
    </div>
    <div class="col-md-3">
      <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
    </div>
  </div>

  <div class="row mx-5 mt-4 mx-auto justify-content-center">
    <div class="col-md-2">
      <%= f.label :ニックネーム %>
    </div>
    <div class="col-md-3">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row mx-5 mt-4 mx-auto justify-content-center">
    <div class="col-md-2">
      <%= f.label :自己紹介文 %>
    </div>
    <div class="col-md-3">
      <%= f.text_area :introduction, class: 'form-control', rows: "5" %>
    </div>
  </div>

  <div class="row mx-5 mt-4 mx-auto justify-content-center">
    <div class="col-md-2">
      <%= f.label :メールアドレス %>
    </div>
    <div class="col-md-3">
      <%= f.text_field :email %>
    </div>
  </div>

  <div class="row mx-5 mt-4 mx-auto justify-content-center">
    <div class="col-md-2">
      <%= f.radio_button :is_deleted, false %>
      <%= f.label :is_deleted, "有効" , value: false %>
      <%= f.radio_button :is_deleted, true %>
      <%= f.label :is_deleted, "退会" , value: true %>
    </div>
  </div>

  <div class="row mx-5 mt-4 mx-auto justify-content-center">
    <div class="actions col-3">
      <%= f.submit class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/admin/customers/index.html.erb
<div class="row mx-auto justify-content-center">
  <div class="col-md-7 offset-md-1 py-3">
    <%= render 'public/searches/searchbox' %>
    <h2>会員一覧</h2>
    <table class="table">
      <thead>
        <tr>
          <th>画像</th>
          <th>ニックネーム</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= image_tag customer.get_profile_image(50, 50) %></td>
            <td><%= customer.name %></td>
            <td><%= link_to "show", admin_customer_path(customer), class: 'btn btn-success' %></td>
            <td>投稿件数：<%= customer.sakes.count %></td>
            <td>
              <% if customer.is_deleted == true %>
                ステータス：<p class="text-secondary">退会済み</p>
              <% else %>
                ステータス：<p class="text-success">有効</p>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row mx-auto justify-content-center">
  <div class="col-5 d-flex mx-auto">
    <%= paginate @customers, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="m-5">
  <h2 class="col-sm-5">会員情報</h2>
</div>
<div class="row">
  <p class="offset-1 col-sm-2"><strong>登録情報</strong></p>
  <p class="col-sm-3"><%= link_to "編集する", edit_admin_customer_path, class: 'btn btn-success' %></p>
</div>
<div class="row mx-auto justify-content-center">
  <div class="offset-md-1 col-md-11">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td class="bg-light" width="30%">プロフィール画像</td>
          <td width="70%"><%= image_tag @customer.get_profile_image(100, 100) %></td>
        </tr>
        <tr>
          <td class="bg-light">ニックネーム</td>
          <td><%= @customer.name %></td>
        </tr>
        <tr>
          <td class="bg-light">自己紹介</td>
          <td><%= @customer.introduction %></td>
        </tr>
        <tr>
          <td class="bg-light">メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>