config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'sakes/index'
  end
  root to: 'public/homes#top'
  get "about" => "public/homes#about"
  get "admin" => "admin/homes#top"

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン機能
  devise_scope :customer do
    post 'public/guest_login', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only:[:index,:create,:edit,:update,:destroy]
    resources :sakes, only:[:show,:index,:destroy] do
      resources :sake_comments, only:[:destroy]
    end
    resources :customers, only:[:index,:show,:edit,:update]
    get "homes/about" => "homes#about"
    post "homes/about" => "homes#create"
    resources :homes, only:[:create,:edit,:update,:destroy]
  end

  scope module: :public do
    resources :genres, only:[:index]
    get 'search' => 'searches#search'
    get 'genre_search' => 'sakes#genre_search'
    resources :sakes, only:[:index,:show,:destroy,:edit,:update,:create,:new] do
      resources :sake_comments, only:[:edit,:update,:destroy,:create]
      resource :favorites, only:[:create,:destroy]
      resource :bookmarks, only:[:create,:destroy]
      get 'search' => "genres#search"
    end
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/delete_status' => 'customers#is_deleted'
    resources :customers, only:[:index,:show,:destroy,:edit,:update,:create] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      resource :relationships, only:[:destroy,:create]
    end
    resources :chats, only:[:show, :create]
    resources :tags, only:[:create,:destroy]
  end
end

app/models/sake_comment.rb
class SakeComment < ApplicationRecord

  belongs_to :customer
  belongs_to :sake

  validates :comment, presence:true

end

app/controllers/admin/sake_comments_controller.rb
class Admin::SakeCommentsController < ApplicationController
  before_action :authenticate_admin!
  def destroy
    @sake = Sake.find(params[:sake_id])
    SakeComment.find(params[:id]).destroy
  end
end

app/helpers/admin/sake_comments_helper.rb
module Admin::SakeCommentsHelper
end

app/views/admin/sake_comments/_comment.html.erb
<div id="sake_comments">
  <table class="table table-borderless">
    <thead>
      <tr>
        <th width="30%"></th>
        <th width="40%"></th>
        <th width="20%"></th>
      </tr>
    </thead>
    <% sake.sake_comments.each do |sake_comment| %>
      <tr>
        <td>
          <%= link_to admin_customer_path(sake_comment.customer) do %>
            <%= image_tag sake_comment.customer.get_profile_image(50, 50) %><br>
            <%= sake_comment.customer.name %>|<%= sake_comment.created_at.strftime('%Y/%m/%d') %>
          <% end %>
        </td>
        <td><%= sake_comment.comment %></td>
        <td>
          <%= link_to "削除", admin_sake_sake_comment_path(sake_comment.sake, sake_comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger", remote: true %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/sake_comments/destroy.js.erb
$("#comments_count").html("コメント数: <%= @sake.sake_comments.count %>");
$("#sake_comments").html("<%= j(render 'admin/sake_comments/comment', sake: @sake) %>");
$("#book_comment_comment").val("");