config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'sakes/index'
  end
  root to: 'public/homes#top'
  get "about" => "public/homes#about"
  get "admin" => "admin/homes#top"

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン機能
  devise_scope :customer do
    post 'public/guest_login', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only:[:index,:create,:edit,:update,:destroy]
    resources :sakes, only:[:show,:index,:destroy] do
      resources :sake_comments, only:[:destroy]
    end
    resources :customers, only:[:index,:show,:edit,:update]
    get "homes/about" => "homes#about"
    post "homes/about" => "homes#create"
    resources :homes, only:[:create,:edit,:update,:destroy]
  end

  scope module: :public do
    resources :genres, only:[:index]
    get 'search' => 'searches#search'
    get 'genre_search' => 'sakes#genre_search'
    resources :sakes, only:[:index,:show,:destroy,:edit,:update,:create,:new] do
      resources :sake_comments, only:[:edit,:update,:destroy,:create]
      resource :favorites, only:[:create,:destroy]
      resource :bookmarks, only:[:create,:destroy]
      get 'search' => "genres#search"
    end
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/delete_status' => 'customers#is_deleted'
    resources :customers, only:[:index,:show,:destroy,:edit,:update,:create] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      resource :relationships, only:[:destroy,:create]
    end
    resources :chats, only:[:show, :create]
    resources :tags, only:[:create,:destroy]
  end
end

app/models/sake.rb
class Sake < ApplicationRecord

  belongs_to :customer
  belongs_to :genre, optional: true
  belongs_to :tag, optional: true
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :sake_comments, dependent: :destroy

  validates :name, presence:true
  validates :introduction, presence:true
  validates :genre_id, presence:true
  # URLでAmazonがある時のみ許可
  validates :url, format: { with: /https:\/\/www\.amazon\.co\.jp.*/ }, allow_blank: true

  has_one_attached :sake_image

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def bookmarked_by?(customer)
    bookmarks.exists?(customer_id: customer.id)
  end

  # 画像がない場合、no_image
  def get_sake_image(width, height)
    unless sake_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      sake_image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    sake_image.variant(resize_to_limit: [width, height]).processed
  end

  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @sake = Sake.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @sake = Sake.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @sake = Sake.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @sake = Sake.where("name LIKE?","%#{word}%")
    else
      @sake = Sake.all
    end
  end
end

app/controllers/admin/sakes_controller.rb
class Admin::SakesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @sakes = Sake.page(params[:page]).per(20)
  end

  def show
    @sake = Sake.find(params[:id])
    @genre = @sake.genre
  end

  def destroy
    @sake = Sake.find(params[:id])
    @sake.destroy
    redirect_to admin_sakes_path
  end
end

app/helpers/admin/sakes_helper.rb
module Admin::SakesHelper
end

app/views/admin/sakes/index.html.erb
<div class="m-5">
  <div class="row mx-auto justify-content-center">
    <div class="col-md-11 offset-md-1">
      <h2>投稿一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th width="8%">image</th>
            <th width="15%">name/genre</th>
            <th width="30%">introduction</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @sakes.order(created_at: :desc).each do |sake| %>
            <tr>
              <td><%= image_tag sake.get_sake_image(50, 50) %><p class="font-6">投稿日：<%= sake.created_at.strftime('%Y/%m/%d') %></p></td>
              <td><p><%= sake.name %><br><%= sake.genre.name %></p></td>
              <td><%= sake.introduction %></td>
              <td><%= render "public/sakes/static_rate", sake: sake %><br><%= render "public/sakes/url", sake: sake %></td>
              <td>♥<%= sake.favorites.count %><br><i class="fas fa-light fa-comment"></i><%= sake.sake_comments.count %></td>
              <td>
                <%= link_to "内容", admin_sake_path(sake.id), class: 'btn btn-sm btn-success' %>
                <%= link_to "削除", admin_sake_path(sake.id), method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'btn btn-sm btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row mx-auto justify-content-center">
    <div class="col-11 offset-md-1 d-flex mx-auto">
      <%= paginate @sakes, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/admin/sakes/show.html.erb
<div class="row m-5 mx-auto justify-content-center">
  <div class="col-2">
    <p>
      投稿者:
      <%= link_to admin_customer_path(@sake.customer) do %>
        <%= @sake.customer.name %><br>
        <%= image_tag @sake.customer.get_profile_image(100, 100) %>
      <% end %>
    </p>
  </div>
  <div class="col-6">
    <p>投稿日：<%= @sake.created_at.strftime('%Y/%m/%d') %></p>
    <p>お酒の名前：<%= @sake.name %><br></p>
    <p>ジャンル：<%= @genre.name %><br></p>
    <p>紹介文：<br><%= @sake.introduction %><br></p>
    <p><%= render "public/sakes/url", sake: @sake %></p>
    <p>評価：<%= render "public/sakes/static_rate", sake: @sake %><br></p>
  </div>
</div>

<div class="row mx-sauto justify-content-center">
  <div class="col-10">
    <p id="comments_count">コメント件数 : <%= @sake.sake_comments.count %></p>
  </div>
</div>

<div class="row mb-5 mx-auto justify-content-center">
  <div class="offset-md-1 col-md-10">
    <p>コメント蘭</p>
    <%= render "admin/sake_comments/comment", sake: @sake %>
  </div>
</div>