config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'sakes/index'
  end
  root to: 'public/homes#top'
  get "about" => "public/homes#about"
  get "admin" => "admin/homes#top"

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # ゲストログイン機能
  devise_scope :customer do
    post 'public/guest_login', to: 'public/sessions#guest_sign_in'
  end

  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only:[:index,:create,:edit,:update,:destroy]
    resources :sakes, only:[:show,:index,:destroy] do
      resources :sake_comments, only:[:destroy]
    end
    resources :customers, only:[:index,:show,:edit,:update]
    get "homes/about" => "homes#about"
    post "homes/about" => "homes#create"
    resources :homes, only:[:create,:edit,:update,:destroy]
  end

  scope module: :public do
    resources :genres, only:[:index]
    get 'search' => 'searches#search'
    get 'genre_search' => 'sakes#genre_search'
    resources :sakes, only:[:index,:show,:destroy,:edit,:update,:create,:new] do
      resources :sake_comments, only:[:edit,:update,:destroy,:create]
      resource :favorites, only:[:create,:destroy]
      resource :bookmarks, only:[:create,:destroy]
      get 'search' => "genres#search"
    end
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/delete_status' => 'customers#is_deleted'
    resources :customers, only:[:index,:show,:destroy,:edit,:update,:create] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      resource :relationships, only:[:destroy,:create]
    end
    resources :chats, only:[:show, :create]
    resources :tags, only:[:create,:destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence:true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :customer
  belongs_to :sake

end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :customer
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140}

end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sakes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :sake_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :dm_rooms
  has_many :chats
  has_many :room, through: :dm_rooms

  validates :name, presence:true, length: { minimum: 1, maximum: 20 }
  validates :email, presence:true

  has_one_attached :profile_image

  # 画像ファイルについて
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # ゲストログイン機能
  def self.guest
    find_or_create_by!(name: 'guest' ,email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guest"
    end
  end

  # フォローフォロワー機能
  def follow(customer)
    relationships.create(followed_id: customer.id)
  end

  def unfollow(customer)
    relationships.find_by(followed_id: customer.id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end

  #退会機能
  # is_deletedがfalseならtrueを返すようにしている
  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約を設ける
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("name LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end
end

app/models/dm_room.rb
class DmRoom < ApplicationRecord

  belongs_to :customer
  belongs_to :room

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :sake

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :sakes, dependent: :destroy

  validates :name, presence:true

  def self.search_for(content)
    genres = Genre.where("name LIKE?", "#{content}")
    genres.inject(init = []){|result, name| result + name.sakes}
  end
end

app/models/home.rb
class Home < ApplicationRecord

  validates :name, presence:true
  validates :introduction, presence:true

  has_one_attached :image

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :dm_rooms
  has_many :chats

end

app/models/sake.rb
class Sake < ApplicationRecord

  belongs_to :customer
  belongs_to :genre, optional: true
  belongs_to :tag, optional: true
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :sake_comments, dependent: :destroy

  validates :name, presence:true
  validates :introduction, presence:true
  validates :genre_id, presence:true
  # URLでAmazonがある時のみ許可
  validates :url, format: { with: /https:\/\/www\.amazon\.co\.jp.*/ }, allow_blank: true

  has_one_attached :sake_image

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def bookmarked_by?(customer)
    bookmarks.exists?(customer_id: customer.id)
  end

  # 画像がない場合、no_image
  def get_sake_image(width, height)
    unless sake_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      sake_image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    sake_image.variant(resize_to_limit: [width, height]).processed
  end

  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @sake = Sake.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @sake = Sake.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @sake = Sake.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @sake = Sake.where("name LIKE?","%#{word}%")
    else
      @sake = Sake.all
    end
  end
end

app/models/sake_comment.rb
class SakeComment < ApplicationRecord

  belongs_to :customer
  belongs_to :sake

  validates :comment, presence:true

end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :name, presence:true

  has_many :sakes, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end


  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/sakes_helper.rb
module Admin::SakesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件のエラー") %> を検出しました。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="image_tag">
  <% if admin_signed_in? %>
    <nav class="navbar navbar-expand-md navbar-light bg-warning">
  <% else %>
    <nav class="navbar navbar-expand-md navbar-light bg-dark">
  <% end %>

    <div class="container-fluid">
      <%= link_to root_path, class:'btn btn-outline-light bg-dark text-white mr-3 logotitle font-16' do %>Al-comi<% end %>
      <% if customer_signed_in? %>
        <%= link_to '新規投稿', new_sake_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3 w-100px new-form' %>
      <% end %>
      <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon bg-white"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <!--ログインしたとき-->
        <% if customer_signed_in? %>
          <p class="text-left text-light ml-5 customer-name mt-3">ようこそ、<%= current_customer.name %>さん！</p>
        <% end %>
        <% if admin_signed_in? %>
          <h3 class="text-left text-dark ml-5 customer-name">管理者画面</h3>
        <% end %>

        <ul class="navbar-nav ml-auto">
          <!--customerでログインしている時-->
          <% if customer_signed_in? %>
            <li><%= link_to '新規投稿', new_sake_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3 w-100px new-form-hang' %></li>
            <li><%= link_to 'マイページ', customer_path(current_customer), class:'btn btn-outline-light bg-dark text-white mr-3 my-3 w-100px' %></li>
            <li><%= link_to 'お酒一覧', sakes_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3' %></li>
            <li><%= link_to '会員一覧', customers_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3' %></li>
            <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class:'btn btn-outline-light bg-dark text-warning mr-3 my-3' %></li>
          <!--adminでログインしている時-->
          <% elsif admin_signed_in? %>
            <li><%= link_to 'アバウト', admin_homes_about_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3' %></li>
            <li><%= link_to '会員一覧', admin_customers_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3'  %></li>
            <li><%= link_to '投稿一覧', admin_sakes_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3'  %></li>
            <li><%= link_to 'ジャンル一覧', admin_genres_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3'  %></li>
            <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:'btn btn-outline-light bg-dark text-warning my-3' %></li>
          <!--ログインしていない状態-->
          <% else %>
            <li><%= link_to 'お酒一覧', sakes_path, class:'btn btn-outline-light bg-dark text-white mr-3 my-3' %></li>
            <li><%= link_to 'アバウト', about_path, class:'btn btn-outline-light bg-dark text-whitee mr-3 my-3' %></li>
            <li><%= link_to 'ログイン', new_customer_session_path,  class:'btn btn-outline-light bg-dark text-warning mr-3 my-3' %></li>
            <li><%= link_to '新規登録', new_customer_registration_path, class:'btn btn-outline-dark bg-white mr-3 my-3' %></li>
            <li><%= link_to 'ゲストログイン（閲覧用）', public_guest_login_path, class: "btn btn-outline-light bg-dark text-white mr-3 my-3", method: :post %></li>
            <li><%= link_to '管理者ログイン', admin_session_path,  class:'btn btn-outline-light bg-dark text-warning mr-3 my-3' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PfApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="body">
      <div class="container-fluid">
        <div class="text-center">
          <%= flash[:notice] %>
          <%= alert %>
        </div>
        <%= yield %>
      </div>
      <span id="back">
        <a href="#">
          <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=>false}, class: "arrow" %>
        </a>
      </span>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>